"""add task.name column

Revision ID: 627f339d872a
Revises: 
Create Date: 2025-08-28 22:25:21.741464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627f339d872a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('task_time', sa.Time(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
