"""make title nullable

Revision ID: ba77d3f9772b
Revises: ae7f4900c8e0
Create Date: 2025-09-05 18:03:53.927497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba77d3f9772b'
down_revision = 'ae7f4900c8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
